### ISSUE TITLE
pip install -e?

### ISSUE THREAD

**Issue by mr-devs** [truthy/osometweet#10]
@yangkcatiu you mentioned in the `user-lookup` branch `README.md` ...

> ### Local development
> Clone this project, go to the source directory, type the following command to install the package locally:
> ```bash
> pip install -e ./
> ```

Can you help me understand what this does exactly? The [pip documentation](https://pip.pypa.io/en/stable/reference/pip_install/#install-editable) says...

<img width="743" alt="image" src="https://user-images.githubusercontent.com/48068852/102720681-b9e85880-42c3-11eb-98ac-d0347a5c16de.png">

... which isn't very helpful.

From other Googling, it seems like maybe this allows me to import the version of the package that is present in the source folder on my local machine. Whereas, if I don't do this, running `import osometweet` would give me whatever the latest version of the package was when pushed to PyPi? I just tried this out and it seems like that is at least one difference, is there anything else that this does?

**Comment by yangkcatiu** [comment]
Oh, my bad, the `/` at the end is not supposed to be there.

**Comment by yangkcatiu** [comment]
Please close the issue if it's working now
