### ISSUE TITLE
Implement OAuth 1.0a

### ISSUE THREAD

**Issue by ChrisTorresLugo** [truthy/osometweet#2]
Currently, osometweet only supports authentication through [OAuth 2.0 bearer token](https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens). This form of authentication only allows for read-access. Performing any action that requires write-access, such as BotSlayer's send DM functionality, or accessing non-public fields, such as private engagement metrics, will be rejected by the API. 

To solve this issue, we have to implement [OAuth 1.0a](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/oauth-echo). Ideally, the library will check whether the requested fields are allowed under the instance's authentication prior to calling the API. e.g. raise an error if authenticated using OAuth 2.0 and trying to post a tweet.

**Comment by mr-devs** [comment]
This is addressed in PR #4
