### ISSUE TITLE
Batch Compliance

### ISSUE THREAD

**Issue by rachithaiyappa** [truthy/osometweet#93]
Feature Request: 
Integrating [batch compliance](https://developer.twitter.com/en/docs/twitter-api/compliance/batch-compliance/introduction) into the osometweet package

This feature allows the user to get the compliance event type for each ID in a batch of User IDs or Tweet IDs. The compliance event are listed [here](https://developer.twitter.com/en/docs/twitter-api/compliance/batch-compliance/introduction)

I don't mind working on this and submitting a PR.

**Comment by mr-devs** [comment]
You are certainly welcome to work on and submit your own PR. Given the latest release of `Tweepy` we have not been really been trying to maintain this (although there are definitely some things we have that I wish Tweepy had). 

I am curious - what do you want to use this for?

**Comment by mr-devs** [comment]
Also, you probably saw but if you submit a PR, please try and tick off as many of the boxes listed in the [contributing file](https://github.com/osome-iu/osometweet/blob/master/CONTRIBUTING.md). I would say that the most important are docstrings, tests, and Wiki examples. Thanks!

**Comment by rachithaiyappa** [comment]
> I am curious - what do you want to use this for?

Was trying to identify some users in a dataset and the top users (whatever top means) are all either suspended/delted....

So just wanted an automated way to check who exits to move on....

**Comment by mr-devs** [comment]
Gotcha. You can also use [this script](https://github.com/osome-iu/osometweet/blob/master/examples/user-lookup-ids.py) to pull user information. It saves user information for who is still active in one file and — for those who can't be found — it saves the errors returned by Twitter in a separate file. These errors will contain information like "suspended", "user ID can't be found" etc...

I originally asked b/c according to the link you shared above, you're technically only allowed to use the batch compliance endpoint to check what data should be removed from some sort of database — though I suppose there really is no way for Twitter to know this...

Here is what I'm referring to...
> These batch compliance endpoints allow you to upload large datasets of Tweet or user IDs to retrieve their compliance status in order to determine what data requires action in order to bring your datasets into compliance. Please note, use of the batch compliance endpoints is restricted to aforementioned use cases, and any other purpose is prohibited and may result in enforcement action.

**Comment by rachithaiyappa** [comment]
The script you linked is what I was looking for! I vaguely remember using something for our superspreaders project months ago but was unsure if I'd written one for v1 or v2. Now that you've pointed me to it I don't plan on working on this issue.
I guess we can close this issue unless Jack wants to work on it...

**Comment by mr-devs** [comment]
Yeah, I basically wrote that script for the super-spreaders project.

I am going to close the issue because, in reality, this is a really low-priority feature request (I think data gathering endpoints are more important). That said, if Jack wants to work on it he can still make the PR when it's ready to be reviewed. Thanks!
